services:
  postgres:
    container_name: postgres
    image: postgres:16-alpine
    env_file:
      - '.env'
    healthcheck:
      test: ['CMD', 'pg_isready -U admin -d test']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file:
      - '.env'
    ports:
      - 5050:80
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
