services:
  postgres:
    container_name: postgres
    image: postgres:16-alpine
    env_file:
      - '.env'
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - postgres

  retail.server:
    container_name: retail.server
    image: ghcr.io/khariton90/retail-server:latest
    env_file:
      - '.env'
    depends_on:
      - postgres
    ports:
      - 3001:3001
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
